apiVersion: 1

datasources:
  - name: InfluxDB_Telegraf
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: grafana_org_name
      defaultBucket: telegraf
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: TOKEN_VALUE

